[package]
name = "db_adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
indexmap = { workspace = true }
patriecia = { workspace = true }
parking_lot = { workspace = true }
